#!/bin/bash
# My example bash script
echo "Running post-processing..."

docker run -it --rm -v "$(pwd)":/home/openfoam/data dicehub/openfoam:opencfd-2306 "cd data; postProcess -case . -func probingLine1 -region  ExtAirTop          -latestTime  "
docker run -it --rm -v "$(pwd)":/home/openfoam/data dicehub/openfoam:opencfd-2306 "cd data; postProcess -case . -func probingLine1 -region  ExtAirBottom -latestTime"
docker run -it --rm -v "$(pwd)":/home/openfoam/data dicehub/openfoam:opencfd-2306 "cd data; postProcess -case . -func probingLine1 -region  IntairTop -latestTime"
docker run -it --rm -v "$(pwd)":/home/openfoam/data dicehub/openfoam:opencfd-2306 "cd data; postProcess -case . -func probingLine1 -region  IntairBottom -latestTime"
docker run -it --rm -v "$(pwd)":/home/openfoam/data dicehub/openfoam:opencfd-2306 "cd data; postProcess -case . -func probingLine1 -region  Brick -latestTime"
docker run -it --rm -v "$(pwd)":/home/openfoam/data dicehub/openfoam:opencfd-2306 "cd data; postProcess -case . -func probingLine1 -region  Insulation -latestTime"
docker run -it --rm -v "$(pwd)":/home/openfoam/data dicehub/openfoam:opencfd-2306 "cd data; postProcess -case . -func probingLine1 -region  ConcreteTop -latestTime"
docker run -it --rm -v "$(pwd)":/home/openfoam/data dicehub/openfoam:opencfd-2306 "cd data; postProcess -case . -func probingLine1 -region  ConcreteBottom -latestTime"
docker run -it --rm -v "$(pwd)":/home/openfoam/data dicehub/openfoam:opencfd-2306 "cd data; postProcess -case . -func probingLine1 -region  Slab -latestTime"
docker run -it --rm -v "$(pwd)":/home/openfoam/data dicehub/openfoam:opencfd-2306 "cd data; postProcess -case . -func probingLine1 -region  Plaster -latestTime"
docker run -it --rm -v "$(pwd)":/home/openfoam/data dicehub/openfoam:opencfd-2306 "cd data; postProcess -case . -func probingLine2 -region  ExtAirTop          -latestTime"
docker run -it --rm -v "$(pwd)":/home/openfoam/data dicehub/openfoam:opencfd-2306 "cd data; postProcess -case . -func probingLine2 -region  ExtAirBottom -latestTime"
docker run -it --rm -v "$(pwd)":/home/openfoam/data dicehub/openfoam:opencfd-2306 "cd data; postProcess -case . -func probingLine2 -region  IntairTop -latestTime"
docker run -it --rm -v "$(pwd)":/home/openfoam/data dicehub/openfoam:opencfd-2306 "cd data; postProcess -case . -func probingLine2 -region  IntairBottom -latestTime"
docker run -it --rm -v "$(pwd)":/home/openfoam/data dicehub/openfoam:opencfd-2306 "cd data; postProcess -case . -func probingLine2 -region  Brick -latestTime"
docker run -it --rm -v "$(pwd)":/home/openfoam/data dicehub/openfoam:opencfd-2306 "cd data; postProcess -case . -func probingLine2 -region  Insulation -latestTime"
docker run -it --rm -v "$(pwd)":/home/openfoam/data dicehub/openfoam:opencfd-2306 "cd data; postProcess -case . -func probingLine2 -region  ConcreteTop -latestTime"
docker run -it --rm -v "$(pwd)":/home/openfoam/data dicehub/openfoam:opencfd-2306 "cd data; postProcess -case . -func probingLine2 -region  ConcreteBottom -latestTime"
docker run -it --rm -v "$(pwd)":/home/openfoam/data dicehub/openfoam:opencfd-2306 "cd data; postProcess -case . -func probingLine2 -region  Slab -latestTime"
docker run -it --rm -v "$(pwd)":/home/openfoam/data dicehub/openfoam:opencfd-2306 "cd data; postProcess -case . -func probingLine2 -region  Plaster -latestTime"
docker run -it --rm -v "$(pwd)":/home/openfoam/data dicehub/openfoam:opencfd-2306 "cd data; postProcess -case . -func probingLine3 -region  ExtAirTop          -latestTime"
docker run -it --rm -v "$(pwd)":/home/openfoam/data dicehub/openfoam:opencfd-2306 "cd data; postProcess -case . -func probingLine3 -region  ExtAirBottom -latestTime"
docker run -it --rm -v "$(pwd)":/home/openfoam/data dicehub/openfoam:opencfd-2306 "cd data; postProcess -case . -func probingLine3 -region  IntairTop -latestTime"
docker run -it --rm -v "$(pwd)":/home/openfoam/data dicehub/openfoam:opencfd-2306 "cd data; postProcess -case . -func probingLine3 -region  IntairBottom -latestTime"
docker run -it --rm -v "$(pwd)":/home/openfoam/data dicehub/openfoam:opencfd-2306 "cd data; postProcess -case . -func probingLine3 -region  Brick -latestTime"
docker run -it --rm -v "$(pwd)":/home/openfoam/data dicehub/openfoam:opencfd-2306 "cd data; postProcess -case . -func probingLine3 -region  Insulation -latestTime"
docker run -it --rm -v "$(pwd)":/home/openfoam/data dicehub/openfoam:opencfd-2306 "cd data; postProcess -case . -func probingLine3 -region  ConcreteTop -latestTime"
docker run -it --rm -v "$(pwd)":/home/openfoam/data dicehub/openfoam:opencfd-2306 "cd data; postProcess -case . -func probingLine3 -region  ConcreteBottom -latestTime"
docker run -it --rm -v "$(pwd)":/home/openfoam/data dicehub/openfoam:opencfd-2306 "cd data; postProcess -case . -func probingLine3 -region  Slab -latestTime"
docker run -it --rm -v "$(pwd)":/home/openfoam/data dicehub/openfoam:opencfd-2306 "cd data; postProcess -case . -func probingLine3 -region  Plaster -latestTime"

